// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MonthlyClaimSystem_PartTwo.Data;

#nullable disable

namespace MonthlyClaimSystem_PartTwo.Migrations
{
    [DbContext(typeof(MonthlyClaimSystem_PartTwoContext))]
    partial class MonthlyClaimSystem_PartTwoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MonthlyClaimSystem_PartTwo.Models.ClaimReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewerRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("ClaimReview");
                });

            modelBuilder.Entity("MonthlyClaimSystem_PartTwo.Models.Coordinator", b =>
                {
                    b.Property<int>("CoordinatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoordinatorId"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<int>("LecturerClaimId")
                        .HasColumnType("int");

                    b.HasKey("CoordinatorId");

                    b.HasIndex("LecturerClaimId");

                    b.ToTable("Coordinator");
                });

            modelBuilder.Entity("MonthlyClaimSystem_PartTwo.Models.FileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsEncrypted")
                        .HasColumnType("bit");

                    b.Property<int?>("LecturerClaimId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LecturerClaimId");

                    b.ToTable("FileModel");
                });

            modelBuilder.Entity("MonthlyClaimSystem_PartTwo.Models.Lecturer", b =>
                {
                    b.Property<int>("ClaimId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClaimId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("ClaimName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Faculty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("HoursWorked")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LecturerRefID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReviewedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReviewedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("SubmittedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ClaimId");

                    b.ToTable("Lecturer");
                });

            modelBuilder.Entity("MonthlyClaimSystem_PartTwo.Models.Manager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<int>("LecturerClaimId")
                        .HasColumnType("int");

                    b.HasKey("ManagerId");

                    b.HasIndex("LecturerClaimId");

                    b.ToTable("Manager");
                });

            modelBuilder.Entity("MonthlyClaimSystem_PartTwo.Models.ClaimReview", b =>
                {
                    b.HasOne("MonthlyClaimSystem_PartTwo.Models.Lecturer", "Lecturer")
                        .WithMany("Reviews")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("MonthlyClaimSystem_PartTwo.Models.Coordinator", b =>
                {
                    b.HasOne("MonthlyClaimSystem_PartTwo.Models.Lecturer", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("MonthlyClaimSystem_PartTwo.Models.FileModel", b =>
                {
                    b.HasOne("MonthlyClaimSystem_PartTwo.Models.Lecturer", null)
                        .WithMany("UploadedFiles")
                        .HasForeignKey("LecturerClaimId");
                });

            modelBuilder.Entity("MonthlyClaimSystem_PartTwo.Models.Manager", b =>
                {
                    b.HasOne("MonthlyClaimSystem_PartTwo.Models.Lecturer", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("MonthlyClaimSystem_PartTwo.Models.Lecturer", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("UploadedFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
